[project]
name = "smartbrowser"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "browser-use>=0.1.36",
    "gradio>=5.16.0",
    "langchain-ollama>=0.2.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
]
